name: 'Configure conda'
description: 'Installs and configures conda.'

inputs:
  initializeShell:
    description: 'Indicates if the shell should be initialized. This should be done the first time this action runs in a worker'
    required: false
    default: 'true'
  condaFile:
    description: 'Conda file for the environment to create, if any.'
    required: false
    default: ''
  envName:
    description: 'Name of the environemnt to create, if any. This name is used if a name is also indicated in `condaFile`'
    required: false
    default: ''
  activate:
    description: 'Inidicates if the environment has to be activated. If no environment is provided, this affects the `base` environment.'
    required: false
    default: 'false'
  pythonVersion:
    description: 'Version of Python to use. If indicated at `condaFile`, then that one is used.'
    required: false
    default: '3.8'

runs:
  using: "composite"
  steps:
    - name: Configuring Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.pythonVersion }}
    - name: Preparing conda
      shell: bash
      run: . ${{ github.action_path }}/action.sh ${{ inputs.initializeShell }} "${{ inputs.envName }}" ${{ inputs.pythonVersion }} ${{ inputs.activate }} "${{ inputs.condaFile }}"